wrange: 2000. 30000.
vmicro: -1
grids: ['f_dr16-apo1','f_dr16-apo2','f_dr16-apo3','f_dr16-apo4','f_dr16-apo5']
f_dr16-apo1:
       type: 'marcs'
       tteff: 11 3500.    250.
       tlogg: 10    0.0     0.5
       tfeh:  15   -2.5     0.25
       tafe:   8   -0.75    0.25
       tcfe:  11   -1.50    0.25
f_dr16-apo2:
       type: 'marcs'
       tteff: 11 3000.    100.
       tlogg:  8   -0.5     0.5
       tfeh:  15   -2.5     0.25
       tafe:   8   -0.75    0.25
       tcfe:  11   -1.50    0.25
f_dr16-apo3:
       type: 'marcs'
       tteff: 11 5500.    250.
       tlogg:  7    2.5     0.5
       tfeh:  15   -2.5     0.25
       tafe:   8   -0.75    0.25
       tcfe:   5   -0.50    0.25
f_dr16-apo4:
       type: 'marcs'
       tteff: 11 3500.    250.
       tlogg:  7    2.5     0.5
       tfeh:  15   -2.5     0.25
       tafe:   8   -0.75    0.25
       tcfe:   5   -0.50    0.25
f_dr16-apo5:
       type: 'marcs'
       tteff: 11 3000.    100.
       tlogg:  7    2.5     0.5
       tfeh:  15   -2.5     0.25
       tafe:   8   -0.75    0.25
       tcfe:   5   -0.50    0.25

