LAMOST:
  gsynth: [
    {'fwhm':167., 'units':'km/s', 'ppr':3., 'wrange':[3800., 9000.] } ]
DESI:
  gsynth: [ 
    {'fwhm': 1.8, 'units': 'A', 'ppr': 3., 'wrange': [3759., 5959], 
    'outsynthfile': 'n_B-DESI.dat'},  
    {'fwhm': 1.8, 'units': 'A', 'ppr': 3., 'wrange': [5635., 7750.],
    'outsynthfile': 'n_R-DESI.dat'},   
    {'fwhm': 1.8, 'units': 'A', 'ppr': 3., 'wrange': [7445., 9843.],
    'outsynthfile': 'n_Z-DESI.dat'} ]
  rewrite_synth: [
    {'synthfile': 'n_B-DESI.dat', 'outsynthfile': 'i_B-DESI.dat'}, 
    {'synthfile': 'n_R-DESI.dat', 'outsynthfile': 'i_R-DESI.dat'},
    {'synthfile': 'n_Z-DESI.dat', 'outsynthfile': 'i_Z-DESI.dat'}]
  merge_synth: [ 
    {'synthfiles': ['i_B-DESI.dat','i_R-DESI.dat','i_Z-DESI.dat'],
     'outsynthfile': 'i_BRZ-DESI.dat'} ]
  synth_rbf:  [ 
    {'synthfile': 'i_BRZ-DESI.dat', 
      'n': 10000, 'rv': False, 'ebv': False}, 
    {'synthfile': 'i_BRZ-DESI.dat',
      'n': 10000, 'rv': False, 'ebv': True} ]
STIS:
  gsynth: [
    {'fwhm': 600., 'units': 'km/s', 'ppr': 3., 'wrange': [3000.,9900.]}] 
R1000:
  gsynth: [
    {'fwhm': 299.792458, 'units': 'km/s', 'ppr': 3., 'wrange': [3000., 11000.] } ]

