DESI: n_sc2-BRZ-DESIrbf.pickle
IDS-R900V: n_sc2-IDS-R900Vrbf.pickle
LAMOST: n_sc2-LAMOSTrbf.pickle
MILES: n_sc2-MILESrbf.pickle
OSIRIS-R2500U: n_sc2-OSIRIS-R2500Urbf.pickle
STIS-NICMOS:  n_sc2-STIS-NICMOSrbf.pickle
XP: n_sc2-XPrbf.pickle
