wrange: 3000. 10000.
vmicro: -1
ncpu: 16
nmerge: 100
keepingz: True
grids: ['f_m2']
f_m2:
       type: 'marcs'
       tteff: 2  2800.    700.
       tlogg: 1   5.0       0.0
       Mg:     2     0.0     0.3
