wrange: 3000. 10000.
vmicro: -1
ncpu: 16
nmerge: 100
keepingz: True
grids: ['f_mkki']
f_mkki:
       type: 'mkk-irregular'
       nmodels: 100
       pteff: 2800.    3500.
       plogg: 0.0       5.0
       pfeh: 0.0      0.0
       Mg:    0.0     0.3
