wrange: 3000. 10000.
vmicro: -1
ncpu: 16
nmerge: 100
grids: ['f_k']
f_k:
       type: 'kurucz'
       tteff: 12  4000.    250.
       tlogg: 11     0.0     0.5
       tfeh:  15    -5.0     0.5
       nchem: 20
       elements: 
           C:  -1. 3. 4200. 4350. 
           Mg: -1. 3. 5150. 5210.

